### ISSUE TITLE
CLI doesn't scaffold correct .env file based on -d option

### ISSUE THREAD

**Issue by keydunov** [statsbotco/cube.js#81] opened 2019-04-16 13:44 UTC
**Describe the bug**
CLI doesn't scaffold correct .env file based on -d option

**To Reproduce**
1. Create new Cube.js app with `cubejs create hello-world -d bigquery`
2. Inspect `.env`
3. It has wrong credential placeholders for BigQuery. 

**Expected behavior**
Correct environment variables placeholders.

**Comment by paveltiunov** [comment] 2019-05-02 20:17
Duplicate of #97

**Closed by paveltiunov** 2019-05-02 20:17 UTC
